### ISSUE TITLE
Weather files aren't being found on Eagle

### ISSUE THREAD

**Issue by aspeake** [NREL/buildstockbatch#144]
**Summary:**
When running on Eagle, all simulations are failing in `BuildExistingModel`, saying the weather file does not exist. The weather files seem to be copied over correctly into the my scratch folder on Eagle (from `/shared-projects/buildstock/weather/project_resstock_national_weather.zip`).

- yml file: https://github.com/NREL/OpenStudio-BuildStock/blob/singleunit/singleunit_inputs/yamls/single_unit_MF.yml 

When running with the `eagle-output-refactor` branch the issue seems to be fixed

**Example error for one simulation (`singularity_output.log`):**
```
Found error in state 'os_measures' with message [":/ruby/2.2.0/gems/openstudio-workflow-1.3.4/lib/openstudio/workflow/util/measure.rb failed with message Runner error :/ruby/2.2.0/gems/openstudio-workflow-1.3.4/lib/openstudio/workflow/util/measure.rb failed with Measure BuildExistingModel reported an error with [\"'/weather/USA_VA_Sterling-Washington.Dulles.Intl.AP.724030_TMY3.epw' does not exist or is not an .epw file.\"],
```

**Platform**
- Simulation platform: Eagle
- BuildStockBatch: 0.16.1
- OpenStudio-BuildStock branch: https://github.com/NREL/OpenStudio-BuildStock/tree/singleunit
- Local Desktop OS: Windows

**Comment by nmerket** [comment]
Will be fixed in #316
