### ISSUE TITLE
Note deprecation of aggregate_timeseries key in documentation

### ISSUE THREAD

**Issue by rHorsey** [NREL/buildstockbatch#175]
**Describe the bug**
The `aggregate_timeseries` key in the `postprocessing` key has been deprecated (https://github.com/NREL/buildstockbatch/blob/develop/buildstockbatch/base.py#L332) but the documentation does not indicate this.

**Expected behavior**
Changelog note, removal from tests, deprecation note in the documentation of the schema and removal from the example schema.

**Platform (please complete the following information):**
- Simulation platform: All
- BuildStockBatch version, branch, or sha: Develop
- OpenStudio-BuildStock version, branch, or sha: N/A
- Local Desktop OS: N/A

**Comment by asparke2** [comment]
This issues was resolved by https://github.com/NREL/buildstockbatch/pull/228, as noted in `changelog_dev.rst`:

```
    .. change::
        :tags: postprocessing
        :pullreq: 228
        :tickets: 182

        Moves the ``eagle.postprocessing.keep_intermediate_files`` to
        ``postprocessing.keep_individual_timeseries`` and changes behavior to
        keep only the timeseries parquet files. Also, removes the deprecated
        ``aggregate_timeseries`` key as that aggregation always happens.
