### ISSUE TITLE
Switch for automatic deletion of time series parquet files

### ISSUE THREAD

**Issue by rHorsey** [NREL/buildstockbatch#182]
**Is your feature request related to a problem? Please describe.**
This [bit of code in the postprocessing](https://github.com/NREL/buildstockbatch/blob/develop/buildstockbatch/postprocessing.py#L365-L368) doesn't have a switch on it and we really really truly need these parquet files for vizstock in particular. The aggregated timeseries files that can be produced from them are useless to us at this point for production runs of ComStock, and soon ResStock.

**Describe the solution you'd like**
A flag to disable this behavior.

**Describe alternatives you've considered**
Making the flag default to not clean up, but I think that's not really reasonable...

**Additional context**
I've spend over 160 hours 'fixing' this for the V1 ComStock run by re-processing over a PB of double-zipped data. I look forward to never doing this ever again.

**Comment by asparke2** [comment]
@rHorsey I believe that this feature was added via:  https://github.com/NREL/buildstockbatch/pull/212, specifically in these lines of code:  https://github.com/NREL/buildstockbatch/pull/212/files#diff-828ab8165bda69957bd58e587d7e6109e847c37d42105953613f25855bf65be9R787-R791

Documentation is under `keep_intermediate_files` here :  https://buildstockbatch.readthedocs.io/en/latest/project_defn.html#eagle-configuration
