### ISSUE TITLE
Move hard-coded Commercial measures into BuildExistingModel

### ISSUE THREAD

**Issue by asparke2** [NREL/buildstockbatch#189]
There are two measures: `add_blinds_to_selected_windows` and `set_space_type_load_subcategories` which are currently [hard-coded into the `create_osw` code](https://github.com/NREL/buildstockbatch/blob/develop/buildstockbatch/workflow_generator/commercial.py#L43-L54).  These should be moved into the `options_lookup.tsv` instead.  This will need to be coordinated with ComStock, where the `options_lookup.tsv` lives.

The corresponding ComStock issue is:  https://github.com/NREL/comstock-internal/issues/41

**Comment by nmerket** [comment]
@asparke2 Can we say this is done then?

**Comment by asparke2** [comment]
@nmerket yep, it's done. Once buildstockbatch is released I'll merge the corresponding [ComStock changes](https://github.com/NREL/comstock-internal/tree/feature/buildstockbatch_v0.20).
