### ISSUE TITLE
Issue creating new bsb environment on eagle - ImportError: GLIBCXX_3.4.21

### ISSUE THREAD

**Issue by rHorsey** [NREL/buildstockbatch#194]
**Describe the bug**
After creating a new environment an error is thrown that reads (in part):
`ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found`

**To Reproduce**
1. Run create_eagle_env.sh on a eagle longin node
2. Run `python -c "import pandas"`

**Expected behavior**
The import to not error

**Solution**
Replace `python=3.7` with `python=3.7.8=hffdb5ce_3_cpython` in https://github.com/NREL/buildstockbatch/blob/develop/create_eagle_env.sh#L29

**Logs**

```
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found
```

**Platform (please complete the following information):**
- Simulation platform: Eagle
- BuildStockBatch version, branch, or sha: https://github.com/NREL/buildstockbatch/commit/451954d48e0c2c749e55a3dcdc1be9a183747f39
- OpenStudio-BuildStock version, branch, or sha: N/A
- Local Desktop OS: N/A

**Additional context**

**Comment by rHorsey** [comment]
I'm not sure if this is going to just 'go away' magically so I'm not putting in a PR - locking the version, particularly the build, is a really double edged sword so I'd like to wait if at all possible...

**Comment by bonnema** [comment]
@rHorsey the default python on Eagle is now 3.7.8
```
ebonnema@el2 ~ $ python --version
Python 3.7.8
ebonnema@el2 ~ $ python -c "import pandas"
ebonnema@el2 ~ $
```
Can't the environment just use the system python?

**Comment by rHorsey** [comment]
I don't think so - stuff with dynamically compiled dependencies tends to break against vanilla eagle python installs on our bastardized centos blends, although maybe that's different now. For some reason when we add in dask, distributed, and ruby to the conda install command (today at least) it jumps us up quite a few symbol version sets for libstdcxx; no clue why but when I force it back to a previous build of cpython the pandas c++ extensions don't try linking to the newer symbol versions.

So I don't forget later - available gnu c++ symbol versions can be retrieved with `strings /usr/lib64/libstdc++.so.6 | grep GLIBCXX` but apparently readelf and objdump are better

**Comment by bonnema** [comment]
@rHorsey understood. What about a middle ground? Replace `python=3.7` with `python=3.7.8` in https://github.com/NREL/buildstockbatch/blob/develop/create_eagle_env.sh#L29?

That seemed to work for me (you can try with `source activate /shared-projects/buildstock/envs/bstock/`).

**Comment by rHorsey** [comment]
Lovely - that seems to work now but it's using the same h8b build of python that was giving me grief yesterday so clearly it's not actually the python build but something tied to the other dependencies... Gah - really nice idea Eric! Do you want to submit a PR with the change? You are the one who came up with an acceptable solution after all! :D
