### ISSUE TITLE
cleanup_sim_dir fails for ComStock with 0.19

### ISSUE THREAD

**Issue by asparke2** [NREL/buildstockbatch#200]
**Describe the bug**
The `enduse_timeseries.csv` file created by ComStock is shown below:

```
time          |electricity_heating_kwh  | gas_heating_kbtu
1/1/2016 0:15 | 0.1234                  | 0.1234
1/1/2016 0:30 | 0.1234                  | 0.1234
```

Prior to [this commit](https://github.com/NREL/buildstockbatch/commit/36d3d27cdb6d3fe4b3a16d016f28f8c8d350f51e), the code was as follows, which assumed that the first column contained timestamps and operated regardless of the column heading was.

```
tsdf = pd.read_csv(timeseries_filepath, parse_dates=[0])
```

Now, the code is as follows, which requires that three columns named `Time, TimeDST, TimeUTC` all be present in the `enduse_timeseries.csv` file or the error `ValueError: 'TimeDST' is not in list` will be thrown.

```
tsdf = pd.read_csv(timeseries_filepath, parse_dates=['Time', 'TimeDST', 'TimeUTC'])
```

**To Reproduce**
1. Run a ComStock run using buildstockbatch 0.19
2. Look at the logs

**Expected behavior**
Process both the ResStock and ComStock `enduse_timeseries.csv` files into parquet format successfully without requiring either to change the format of their files.

**Platform (please complete the following information):**
- Simulation platform: local docker
- BuildStockBatch version, branch, or sha: 0.19
- OpenStudio-BuildStock version, branch, or sha: N/A (local ComStock checkout)
- Local Desktop OS: Windows

**Comment by rajeee** [comment]
Welp! I overlooked the fact that BSB is supposed to process ComStock too when I made that commit.
