### ISSUE TITLE
Upgrade numbering is inconsistent

### ISSUE THREAD

**Issue by Sustainabilist** [NREL/buildstockbatch#215]
Upgrade numbering starts at 2 for results files, and this is confusing and requires special code to deal with for interpreting results. If the first upgrade applied had consistent labeling, that would be more intuitive. 

Example - current state of column names: 

apply_upgrade.run_measure | apply_upgrade_2.run_measure
-- | --

Potential future state: 

apply_upgrade_1.run_measure | apply_upgrade_2.run_measure
-- | --

**Comment by nmerket** [comment]
I'm not sure if this is still an issue, but we should look into it.

**Comment by rajeee** [comment]
The column names have changed in ResStock output and this no longer seems to be an issue.
