### ISSUE TITLE
Potential issue with libbz2 - libbz2.so.1.0.8 (number might be off) missing

### ISSUE THREAD

**Issue by rHorsey** [NREL/buildstockbatch#241]
**Describe the bug**

**I AM NEVER SURE IF THESE THINGS ARE REAL OR JUST ME BUT AS A HEADS UP:**
When building new environments on eagle (post system time) I'm getting an error where pyarrow can't load the so (static object) for libbz2. This appears to have to do with if you pull the libbz2 dependency from anaconda or conda-forge (moments like this remind me why I don't use conda and love the main channel on linux distros.)

If you get this, the fix that worked for me from a clean (i.e. just ssh'ed in) shell:

```sh
module load conda
source activate /path/to/env
conda install -c anaconda bzip2
```

@nmerket 

**To Reproduce**
1. Run create_eagle_env.sh
2. Activate and run with the env from a new shell

**Expected behavior**

```
     _ __         _     __,              _ __
    ( /  )    o  //   /(    _/_       / ( /  )     _/_    /
     /--< , ,,  // __/  `.  /  __ _, /<  /--< __,  /  _, /
    /___/(_/_(_(/_(_/_(___)(__(_)(__/ |_/___/(_/(_(__(__/ /_
      Executing BuildStock projects with grace since 2018
```

**Logs**

Please copy pertinent sections of log files here (e.g. `sampling.out`, `job.out-*`, `postprocessing.out`, `sinularity-output.log`, etc.)

```
log file here
```

**Platform (please complete the following information):**
- Simulation platform: eagle - post August '21 system time
- BuildStockBatch version, branch, or sha: A very old one
- resstock or comstock repo version, branch, or sha: A very custom SPP one
- Local Desktop OS: OSX

**Additional context**
I hit these stupid things quite a bit and I think it may be me not anything else, but just in case.

**Comment by nmerket** [comment]
I can't duplicate this issue. I made an eagle environment last week with no issues. Let me know if it happens again.
