### ISSUE TITLE
Enable retrival of output_variables with just --postprocessonly run

### ISSUE THREAD

**Issue by lixiliu** [NREL/buildstockbatch#244]
It looks like currently we are not able to extract output_variables from the run if they are not already specified in the yml at the beginning of the run. We should be able to extract any output_variables we want with just a post-processing run. I tried rerunning post-processing with a new yml to extract additional output_variables and it does not work for me.

I suspect because the simulation_output jobs' settings do not get updated with respect to the new yml, the post-processing run did not know to extract the new output_variables. I checked one of the simulations_jobXXX.tar file and the old TimeseriesCSVExport setting (the setting specified in my original run) remained in place.

**Comment by nmerket** [comment]
I don't think this is possible. The output variables are sent to EnergyPlus and they aren't available unless you rerun all the simulations.
