### ISSUE TITLE
Allow generating input files only

### ISSUE THREAD

**Issue by shorowit** [NREL/buildstockbatch#249]
It'd be nice if you could use buildstockbatch to create input files (e.g., IDF, OSM, HPXML for ResStock) without running simulations. There is a [confusingly named input called `skip_sims`](https://buildstockbatch.readthedocs.io/en/latest/project_defn.html#baseline-simulations-incl-sampling-algorithm), but it doesn't skip all simulations, just _baseline_ simulations.

I would assume that if this feature was added, it could make use of the OpenStudio CLI run `-m` argument:
```
$ openstudio run --help
Usage: openstudio run [options]

Options:

    -w, --workflow [FILE]            Specify the FILE path to the workflow to run
    -m, --measures_only              Only run the OpenStudio and EnergyPlus measures
    -p, --postprocess_only           Only run the reporting measures
    -s, --socket PORT                Pipe status messages to a socket on localhost PORT
        --debug                      Includes additional outputs for debugging failing workflows and does not clean up the run directory
    -h, --help                       Print this help
```

**Comment by nmerket** [comment]
This is already done https://github.com/NREL/buildstockbatch/blob/develop/buildstockbatch/eagle.py#L705-L709
