### ISSUE TITLE
Write as group ownership rather than user

### ISSUE THREAD

**Issue by afontani** [NREL/buildstockbatch#255]
**Is your feature request related to a problem? Please describe.**
During cleanup of data generated by buildstockbatch on eagle, only users can delete their simulated runs of ResStock or ComStock. For example if `<user>` run ResStock on eagle and write to the `/projects/<handle>` directory, `<user>` is the only one that can delete the files as the user owns the write permissions instead of the group.

The issue comes during cleanup of data and the project directories. A PI or HPC lead does not have the permissions to delete data. Currently, user groups are not supported by HPC admins.

**Describe the solution you'd like**
When copying data from the local scratch of the compute nodes to lustre, make sure that the owner is the group not the user. So possibly using `chown g+rw` after writing data to lustre?

When using `ls -la` **SHOULD NOT** look like:
`-rw-rw----.  1 <user> <handle>   2919 Sep  8 12:13 job.out-72`

When using `ls -la` **SHOULD** look like:
`-rw-rw----.  1 <handle> <handle>   2919 Sep  8 12:13 job.out-72`

**Describe alternatives you've considered**
Adding permission-based user groups --> HPC does not support user groups.

**Additional context**
None

**Comment by rajeee** [comment]
Doesn't seem to be an issue in Kestrel anymore. I just deleted a run folder belonging to someone else (but we are on the same group).
