### ISSUE TITLE
Slow step in bsb process using localdocker

### ISSUE THREAD

**Issue by shorowit** [NREL/buildstockbatch#276]
The ResStock CI runs two essentially identical jobs. Each job consists of 4 ResStock runs spanning ~500 simulations total.
1. `integration-tests`: Job using buildstockbatch with localdocker
2. `analysis-tests`: Job using workflow/run_analysis.rb

You can see an example CI result [here](https://github.com/NREL/resstock/actions/runs/2007367898).

The bsb job takes almost twice as long as the run_analysis.rb job. But if you look closer, the actual time spent running simulations is not very different between the two jobs. Rather, the reason the bsb job takes so much longer is there is an unknown step that takes 10-40 mins for each bsb run.

Here's an excerpt from a bsb run of just 250 simulations. Note that 37 minutes were spent between the two bolded steps. What is bsb doing?

> ...
> Sat, 19 Mar 2022 02:44:40 GMT DEBUG:2022-03-19 02:44:40:buildstockbatch.sampler.residential_quota:Sampling project_national/REEDS Balancing Area...
> Sat, 19 Mar 2022 02:44:40 GMT DEBUG:2022-03-19 02:44:40:buildstockbatch.sampler.residential_quota:Sampling project_national/Generation And Emissions Assessment Region...
> Sat, 19 Mar 2022 02:44:40 GMT DEBUG:2022-03-19 02:44:40:buildstockbatch.sampler.residential_quota:Wrote output file buildstock.csv.
> Sat, 19 Mar 2022 02:44:40 GMT DEBUG:2022-03-19 02:44:40:buildstockbatch.sampler.residential_quota:Sampling took: 0.3 minutes.
> Sat, 19 Mar 2022 02:44:40 GMT DEBUG:2022-03-19 02:44:40:buildstockbatch.sampler.residential_quota:
> Sat, 19 Mar 2022 02:44:40 GMT DEBUG:2022-03-19 02:44:40:buildstockbatch.sampler.residential_quota:Sampling took 18.7 seconds
> Sat, 19 Mar 2022 02:44:40 GMT DEBUG:2022-03-19 02:44:40:buildstockbatch.base:Downloading weather files
> Sat, 19 Mar 2022 02:45:10 GMT DEBUG:2022-03-19 02:45:10:buildstockbatch.base:Extracting weather files to: /home/runner/work/resstock/resstock/project_national/national_baseline/weathermngto5wz
> **Sat, 19 Mar 2022 02:45:42 GMT [Parallel(n_jobs=2)]: Using backend LokyBackend with 2 concurrent workers.
> Sat, 19 Mar 2022 03:22:23 GMT DEBUG:2022-03-19 03:22:23:buildstockbatch.localdocker:Compressing simulation outputs to /home/runner/work/resstock/resstock/project_national/national_baseline/simulation_output/simulations_job0.tar.gz**
> Sat, 19 Mar 2022 03:24:06 GMT [Parallel(n_jobs=2)]: Done   1 tasks      | elapsed:   23.6s
> Sat, 19 Mar 2022 03:24:06 GMT [Parallel(n_jobs=2)]: Done   4 tasks      | elapsed:   40.3s
> Sat, 19 Mar 2022 03:24:06 GMT [Parallel(n_jobs=2)]: Done   9 tasks      | elapsed:  1.6min
> ...

@joseph-robertson @nmerket @rajeee

**Comment by sudeepy** [comment]
Bump. I'm curious about this too, since it could be the same as [my issue](https://github.com/NREL/buildstockbatch/issues/278).

**Comment by nmerket** [comment]
@shorowit The time between the two lines you highlighted _is_ the time spent on simulations. If you look at the `[Parallel(n_jobs=2)]` lines they basically [spit out all at once](https://github.com/NREL/resstock/runs/5608955790?check_suite_focus=true#step:4:243). It's just coming out kind of out of order due to some weirdness around buffered stdout writes from the joblib library that gives those status messages. It's concerning that the runs are taking longer, but that's not it. It's not immediately apparent to me what the slowdown is. Are we indeed running the same buildings and number of buildings in both sets of tests? @joseph-robertson

**Comment by joseph-robertson** [comment]
That's the idea at least - they use the same yml files.

**Comment by shorowit** [comment]
Ah, thanks @nmerket, you're right. So there is not a slow step in the process. But BSB is for some reason taking something like 30-80% longer than the run_analysis.rb runs according to ResStock CI. (Do we expect docker to introduce much overhead?)

@joseph-robertson Is it worth comparing the OSW files produced between BSB and run_analysis.rb for an identical datapoint to see if they are doing anything different? We could also check that they are calling the OS CLI with the same arguments.

**Comment by joseph-robertson** [comment]
Yes. I ran `national_upgrades.yml` with `n_datapoints=1`. Here are OSW files for the "refrigerator" upgrade scenario:
[run_analysis.osw.txt](https://github.com/NREL/buildstockbatch/files/8365602/run_analysis.osw.txt)
[bsb.osw.txt](https://github.com/NREL/buildstockbatch/files/8365607/bsb.osw.txt)

They are essentially identical.

Here are out.osw files:
[out-run_analysis.osw.txt](https://github.com/NREL/buildstockbatch/files/8365707/out-run_analysis.osw.txt)
[out-bsb.osw.txt](https://github.com/NREL/buildstockbatch/files/8365733/out-bsb.osw.txt)

**Comment by joseph-robertson** [comment]
Here is what the OS CLI call looks like for run_analysis.rb: `"C:/openstudio-3.3.0/bin/openstudio.exe" run -w "C:/OpenStudio/resstock/workflow/national_upgrades/run8/national_upgrades-Refrigerator.osw`.

I'm not sure what it looks like for bsb.

**Comment by shorowit** [comment]
Thanks @joseph-robertson. While you're at it, can you also provide the out.osw files from the two runs? They should have timestamps for each processed step of the OSW.

**Comment by joseph-robertson** [comment]
Added above.

**Comment by shorowit** [comment]
Okay, nothing really stands out. BSB just seems to be slower in general.

  | run_analysis.rb | buildstockbatch
-- | -- | --
BuildExistingModel | 21s | 33s
ApplyUpgrade | 18s | 23s
ReportSimulationOutput | 6s | 4s
ReportHPXMLOutput | 1s | 1s
UpgradeCosts | 1s | 1s
QOIReport | 1s | 0s
ServerDirectoryCleanup | 0s | 0s
sum of measures | 48s | 62s
Total | 63s | 76s

![image](https://user-images.githubusercontent.com/5861765/160474935-4f1f4c94-ce78-4286-a070-540b4f9a0eea.png)

**Comment by nmerket** [comment]
> Here is what the OS CLI call looks like for run_analysis.rb: `"C:/openstudio-3.3.0/bin/openstudio.exe" run -w "C:/OpenStudio/resstock/workflow/national_upgrades/run8/national_upgrades-Refrigerator.osw`.
> 
> I'm not sure what it looks like for bsb.

It's basically the same for buildstockbatch. It's almost certainly the overhead of running it in Docker. On Windows/Mac it's in a virtual machine. It shouldn't be as bad on Linux, but I'm sure there's still overhead.

**Comment by shorowit** [comment]
Note that the ResStock CI is on Ubuntu, so it seems like there is still a significant penalty on Linux.

In any case, I think we've looked enough at this -- there isn't anything obviously wrong with the BSB implementation that is causing the differences in runtime. I'm going to close the issue.
