### ISSUE TITLE
Update docs with QOI report

### ISSUE THREAD

**Issue by ejhw** [NREL/buildstockbatch#284]
**Describe the bug**
Docs don't show how to add QOI report to a yaml (like [this](https://github.com/NREL/resstock/blob/develop/project_national/national_upgrades.yml#L41-L42)).

They should also define the qoi metrics you get as outputs.

cc @afontani @nmerket 

**To Reproduce**
1. Project yaml file that exercises the bug.
2. ...

Try to find a minimum reproducible example by isolating features starting with a small, basic run and adding features one by one until you hit the bug. For example, instead of handing over a configuration with 80 upgrades, custom measures, and complex downselect logic, start with a configuration that works and add those things one at a time in small batches until you hit the problem.

**Expected behavior**

**Logs**

Please copy pertinent sections of log files here (e.g. `sampling.out`, `job.out-*`, `postprocessing.out`, `singularity-output.log`, etc.)

```
log file here
```

**Platform (please complete the following information):**
- Simulation platform: [e.g. Eagle, AWS, local docker; please label with this as well]
- BuildStockBatch version, branch, or sha: 
- resstock or comstock repo version, branch, or sha:
- Local Desktop OS: [e.g. Windows, Mac, Linux, especially important if running locally]

**Additional context**

**Comment by joseph-robertson** [comment]
This PR does the first half of your request: https://github.com/NREL/buildstockbatch/pull/274.

**Comment by joseph-robertson** [comment]
Perhaps ResStock reporting measure outputs should be documented in the ResStock documentation.

After discussing, we think it might make sense to move the "Workflow Generator" section out into the ResStock documentation.

**Comment by ejhw** [comment]
> This PR does the first half of your request: #274.

Ah thanks. I search the issues for "documentation" but missed that PR. Moving sounds fine to me.

**Comment by ejhw** [comment]
Will be handled by https://github.com/NREL/buildstockbatch/pull/274
