### ISSUE TITLE
Bintray is no longer available after May 1st. 

### ISSUE THREAD

**Issue by abekhit** [NREL/buildstockbatch#288]
Bintray is no longer live. https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

DockerFile installs Apache Arrow from Bintray. Apache Arrow installation page now uses `jFrog`

```
wget https://apache.jfrog.io/artifactory/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
sudo apt install -y -V ./apache-arrow-apt-source-latest-$(lsb_release --codename --short).deb
```

**Comment by afontani** [comment]
Working on a different workflow in #345 .
