### ISSUE TITLE
Add units to columns in timeseries output

### ISSUE THREAD

**Issue by ejhw** [NREL/buildstockbatch#293]
**Describe the bug**
It looks like units are not present in timeseries output. I'd suggest they get added to avoid confusion, particularly because the units are different for electric and fuel end uses, and are different from the annual outputs. An external user of ResStock results got confused by this because they thought the timeseries output was in mbtu too despite reading the docs.
[Building 1 Baseline Results.csv](https://github.com/NREL/OpenStudio-HPXML/files/8779786/Building.1.Baseline.Results.csv)

[shorowit](https://github.com/shorowit) commented [1 hour ago](https://github.com/NREL/OpenStudio-HPXML/issues/1104#issuecomment-1138665095)
OS-HPXML does have units for timeseries outputs, so bsb or resstock must be losing them.
[results_timeseries.csv](https://github.com/NREL/OpenStudio-HPXML/files/8779850/results_timeseries.csv)

@joseph-robertson
Member
[joseph-robertson](https://github.com/joseph-robertson) commented [1 hour ago](https://github.com/NREL/OpenStudio-HPXML/issues/1104#issuecomment-1138673238)
The units row gets skipped in here: https://github.com/NREL/buildstockbatch/blob/develop/buildstockbatch/base.py#L180-L190, but then units_dict is used later on in https://github.com/NREL/buildstockbatch/blob/develop/buildstockbatch/base.py#L214-L225. Implies units are appended, so I'm not sure what's going on.

cc @ekpresent

**To Reproduce**
1. Project yaml file that exercises the bug.
2. ...

Try to find a minimum reproducible example by isolating features starting with a small, basic run and adding features one by one until you hit the bug. For example, instead of handing over a configuration with 80 upgrades, custom measures, and complex downselect logic, start with a configuration that works and add those things one at a time in small batches until you hit the problem.

**Expected behavior**

**Logs**

Please copy pertinent sections of log files here (e.g. `sampling.out`, `job.out-*`, `postprocessing.out`, `singularity-output.log`, etc.)

```
log file here
```

**Platform (please complete the following information):**
- Simulation platform: [e.g. Eagle, AWS, local docker; please label with this as well]
- BuildStockBatch version, branch, or sha: 
- resstock or comstock repo version, branch, or sha:
- Local Desktop OS: [e.g. Windows, Mac, Linux, especially important if running locally]

**Additional context**

**Comment by ejhw** [comment]
So buildstockbatch removes the units row from raw OS-HPXML timeseries output.

OS-HPXML timeseries output:
<img width="678" alt="image" src="https://user-images.githubusercontent.com/1276021/170526839-f092a835-f1d3-4086-a9ed-908cff681cb0.png">

BSB output:
<img width="562" alt="image" src="https://user-images.githubusercontent.com/1276021/170527835-a17e6f70-bbf7-4912-acd0-a2eb131db8e6.png">


I see two options for preserving units:

1. Preserve the units row in timeseries .parquet files. This will be consistent more with OS-HPXML files. (~~though we are already modifying timestamps~~). This may also be faster?
2. Combine the two header rows into a single row. A single header row will make reading these files slightly easier in Tableau or pandas.

Opinions on this? @rajeee @nmerket @shorowit @afontani @ekpresent

**Comment by nmerket** [comment]
We'll have to do option 2 because parquet files can't have more than one header row like a csv.

**Comment by joseph-robertson** [comment]
I'm confused. Isn't [this](https://github.com/NREL/buildstockbatch/blob/develop/buildstockbatch/base.py#L214-L225) supposed to append units onto the column names?

**Comment by shorowit** [comment]
>     This will be consistent more with OS-HPXML files. (though we are already modifying timestamps).

@ejhw Why are you having to modify timestamps? We added a bunch of timestamp options to OS-HPXML specifically to help ResStock, was it not sufficient?

**Comment by ejhw** [comment]
> > ```
> > This will be consistent more with OS-HPXML files. (though we are already modifying timestamps).
> > ```
> 
> @ejhw Why are you having to modify timestamps? We added a bunch of timestamp options to OS-HPXML specifically to help ResStock, was it not sufficient?

Good point, I forgot about that. I saw three timestamp columns in the bsb output but not in the `results_timeseries.csv` file you uploaded, but looks like we just check for them and don't add them:
https://github.com/NREL/buildstockbatch/blob/515506f7a2fb1e5abb4677c2bcd27631b09271bf/buildstockbatch/base.py#L199-L205

**Comment by ejhw** [comment]
> I'm confused. Isn't [this](https://github.com/NREL/buildstockbatch/blob/develop/buildstockbatch/base.py#L214-L225) supposed to append units onto the column names?

I'm not seeing that new format in the parquet files here: https://s3.console.aws.amazon.com/s3/buckets/resstock-gmlc-bills-lbnl?region=us-west-2&prefix=test-4ups-aps/test-4ups-aps/timeseries/upgrade%3D0/&showversions=false @rajeee  do you know why that might be?

**Comment by rajeee** [comment]
@ejhw  Maybe it was run using older version of BSB?

**Comment by ejhw** [comment]
> @ejhw Maybe it was run using older version of BSB?

@ekpresent Which version of BSB was used for https://s3.console.aws.amazon.com/s3/buckets/resstock-gmlc-bills-lbnl?region=us-west-2&prefix=test-4ups-aps/test-4ups-aps/timeseries/upgrade%3D0/&showversions=false ?

**Comment by ekpresent** [comment]
I used the dev-epresent-hpxml environment which I made from the develop branch of buildstockbatch a few months ago, probably some time in February? Not sure how to check when exactly.

**Comment by nmerket** [comment]
@ekpresent Do the following

```bash
git fetch origin
git merge-base dev-epresent-hpxml origin/develop
```

That should tell you the commit sha that you have in common with the `develop` branch.

**Comment by nmerket** [comment]
That's assuming your branch name is `dev-epresent-hpxml`. If it's not, use whatever branch you're on.

**Comment by ekpresent** [comment]
With some help from Noel, I'm at 

https://github.com/NREL/buildstockbatch/commit/df7cab36697432cee77874ba5f1469b6ab5da8c0

...is that problematically old? I'm never sure when the benefit of updating outweighs the risks.

**Comment by rajeee** [comment]
Timeseries do have units now.
