### ISSUE TITLE
Collect unique errors to an error.csv for how building models fail.

### ISSUE THREAD

**Issue by afontani** [NREL/buildstockbatch#314]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I need to look through all the singularity output files for errors on how building models fail.

**Describe the solution you'd like**
I would like a file with a unique list of error messages. It would be nice if the file is uploaded to AWS and possibly able to query with Athena.

During post-processing, each building model folder is processed to get the data from the data point. It would be nice to insert this new feature during this process.

**Describe alternatives you've considered**
I have not considered another option.

**Additional context**
None.

**Comment by rajeee** [comment]
Related to: https://github.com/NREL/buildstockbatch/issues/379

**Comment by rajeee** [comment]
This is basically taken care of by: https://github.com/NREL/buildstockbatch/pull/437
I have created a follow up request in BSQ: https://github.com/NREL/buildstock-query/issues/49
