### ISSUE TITLE
Sync ResStock/ComStock and BuildStockBatch releases

### ISSUE THREAD

**Issue by afontani** [NREL/buildstockbatch#315]
## Is your feature request related to a problem? Please describe.
I am frustrated when a feature is added to buildstockbatch that break backward compatibility and active projects are forced to update to the latest version of ResStock develop.

## Describe the solution you'd like
@nmerket, @joseph-robertson, and I met and hashed out a tentative plan to get this done.

**Development Instructions**
1. Branch from resstock develop (test-branch)
2. Branch from buildstockbatch develop (test-branch)
3. Point test-branch config to buildstockbatch@test-branch
4. Ensure resstock CI tests are passing
5. Merge buildstockbatch test-branch
6. Release buildstockbatch develop (test-release)
7. Point resstock test-branch config to new buildstockbatch@test-release
8. Merge resstock test-branch

This solves the issue of using an out-of-date resstock that is no longer compatible with buildstockbatch develop. Any out-of-date resstock version points to a specific release of buildstockbatch.

There is still the issue of wanting to use an out-of-date version of resstock, but you need some FIX to buildstockbatch (e.g., some issue with Eagle). Options are to:

1. Get version of resstock up-to-date (i.e., absorb buildstockbatch develop changes)
2. Hotfix buildstockbatch (literally modify a released version of buildstockbatch)

Let’s do this. We will:
1. Release buildstockbatch as it is now
2. Then do items 1 through 8 above
3. Encourage users to either (1) update current resstock projects to develop, or (2) update CI config to whatever appropriate release of buildstockbatch

**Scheduled Releases**
From: buildstockbatch v0.21 (ignore develop’s 0.22)
To: buildstockbatch v2022.10.0 (monthly if changes to develop); then v2022.10.1, v2022.10.2, etc. in the same month; hotfix just follows suffix 1, 2, etc.

**Describe alternatives you've considered**
Subtee and submodule buildstockbatch into resstock develop. This was decided to be more complicated and might still break ResStock projects.

**Additional context**
None.

**Comment by rajeee** [comment]
This is implemented now.

**Comment by joseph-robertson** [comment]
@lixiliu brought up the idea of making this a wiki page.

We should also include our notes/ideas for preserving versions of workflow generators.

**Comment by joseph-robertson** [comment]
I added a "Releases" section to the wiki with some new pages.
