### ISSUE TITLE
Validator request: catch too many options relative to constants.rb

### ISSUE THREAD

**Issue by ekpresent** [NREL/buildstockbatch#329]
constants.rb sets the number of options allowed per upgrade. It used to be 10, it's currently 25. If you have more than that, the simulation will fail. So a nice-to-have feature of the validator would be to catch if any upgrades have more options than the current limit in constants.rb. @rajeee

**Comment by shorowit** [comment]
Related to https://github.com/NREL/resstock/issues/1005
