### ISSUE TITLE
Order results.csvs by building_id

### ISSUE THREAD

**Issue by ekpresent** [NREL/buildstockbatch#331]
A year ago (pre-HPXML), results.csvs were sorted by building_id. They aren't anymore, and in fact the order seems to be re-randomized in each upgrade. It would be great to have them sorted again.

e.g. on a recent test run using the buildstock-2022.10.1 bsb environment, results_up00.csv started with building_id 4249, and results_up01.csv started with building_id 3152. This breaks a lot of old python code that looked at annual savings by just subtracting the columns from different upgrades.

**Comment by afontani** [comment]
@nmerket to try to get this in before the next buildstockbatch release.
