### ISSUE TITLE
HPXML workflow: Support `include_timeseries_unmet_hours` in yaml

### ISSUE THREAD

**Issue by shorowit** [NREL/buildstockbatch#340]
This would allow a user to more easily see when unmet hours occur.

https://github.com/NREL/OpenStudio-HPXML/blob/d999787cff2e8e6a296d83a3802dd2ecdb46f668/ReportSimulationOutput/measure.rb#L112

**Comment by joseph-robertson** [comment]
Hmm, interesting that this argument slipped through the cracks. Anyhow, see linked PR that will close this issue.
