### ISSUE TITLE
Upload buildstock.csv to S3 during postprocessing

### ISSUE THREAD

**Issue by asparke2** [NREL/buildstockbatch#348]
Upload buildstock.csv to S3 during postprocessing.

**Describe the solution you'd like**
Upload buildstock.csv to S3 during postprocessing. This is particularly useful for ComStock since the sample is always precomputed. This makes it easier to postprocess the results. Could also consider uploading the YML file for easier correspondence between runs on Eagle and S3 directories.

**Comment by nmerket** [comment]
See #254
