### ISSUE TITLE
AWS not running the specified batch_array_size in input yaml file

### ISSUE THREAD

**Issue by phgupta** [NREL/buildstockbatch#361]
I ran a large simulation (11,000 buildings with 7 upgrades) and set batch_array_size=100 in the input yaml file. 

I was hoping 100 jobs to be running concurrently in AWS with 77,000 simulations / 100 jobs = 770 simulations per job. However, AWS ran only 36 jobs concurrently. It finished the first round of 36 jobs, then another round of 36 jobs followed by 28 jobs - which ended up taking longer than expected. 

Is 36 the max number of jobs that AWS can handle concurrently? 

The following lines of code in ``aws.py`` show that 10,000 is the maximum number, thus I was hoping the 100 jobs to run concurrently. 
```
# This is the maximum number of jobs that can be in an array
if self.batch_array_size <= 10000:
    max_array_size = self.batch_array_size
else:
    max_array_size = 10000
n_sims_per_job = math.ceil(n_sims / max_array_size)
n_sims_per_job = max(n_sims_per_job, 2)
logger.debug('Number of simulations per array job = {}'.format(n_sims_per_job))
```

Not sure what went wrong. Any help would be appreciated! :)

- Simulation platform: AWS
- BuildStockBatch version, branch, or sha: v0.21
- resstock or comstock repo version, branch, or sha: v2.5.0
- Local Desktop OS: Windows WSL2

**Comment by afontani** [comment]
@nmerket : I thought we also had another minimum number of simulations per job somewhere that would effect the size of the job array. Is this still true?

**Comment by nmerket** [comment]
Yep that's on purpose https://github.com/NREL/buildstockbatch/blob/develop/buildstockbatch/aws/aws.py#L1872-L1873

**Comment by phgupta** [comment]
What's done on purpose again? I don't see any hardcoding of max batch array size to be 36. @nmerket the link you provided checks that the max batch array size is less than 10,000 which in my case it is. Also, there doesn't seem to be any maximum limit on the number of simulations per job. The minimum limit is 2, but in my case 77k/100 = 770 simulations per job exceeds that minimum threshold.

Am I missing something here?

**Comment by nmerket** [comment]
The only code we have that controls that is the code you see there that ensures there's at least 2 simulations per job. It should be running more instances in parallel for you. It's possible you need to request a quota increase from AWS. They limit the number of instances you can have running by default to keep new users from overrunning their costs. That might be the problem.

That being said, the AWS workflow on the master branch is quite broken right now. We're working on fixing it for, but it's still pretty rough. We primarily use Eagle, NREL's supercomputer, for these batch simulations, so the AWS batch version has seen some neglect over the years. Unfortunately we are not in a position where we can provide regular support to community users to run the AWS workflow. In general we provide more support for people using data from our large scale runs like the End Use Savings Shapes project. They can be found [here](https://resstock.nrel.gov/datasets).

**Comment by phgupta** [comment]
Yes, it's possible that could be the issue. I'll look into that. 

Do you know when you're planning on working on the AWS workflow? I'm currently using the AWS workflow for a couple of projects, and more are expected in the pipeline, so a timeline would be super helpful!
