### ISSUE TITLE
Compile errors and possibly warnings during post-processing

### ISSUE THREAD

**Issue by afontani** [NREL/buildstockbatch#379]
**Is your feature request related to a problem? Please describe.**
Currently it is difficult to dig into what building models failed or if any warnings have been thown by the OpenStudio-HPXML workflow. 

**Describe the solution you'd like**
Can we compile a list of errors and warnings for each building ID in a json file or something like that during post-processing?

**Describe alternatives you've considered**
None

**Additional context**
Attempting to figure out what and why buildings failed or have strange warnings more quickly.

**Comment by afontani** [comment]
Maybe this will help: https://github.com/NREL/resstock/pull/1102

**Comment by rajeee** [comment]
This is basically taken care of by: https://github.com/NREL/buildstockbatch/pull/437
I have created a follow up request in BSQ: https://github.com/NREL/buildstock-query/issues/49
