### ISSUE TITLE
Bug fixes for bsb v2023.06.0

### ISSUE THREAD

**Issue by phgupta** [NREL/buildstockbatch#394]
There were a couple of bugs in v2023.01.0 that transferred over to v2023.06.0 too for the AWS workflow. Listing them here in the hopes that they get resolved in the newer versions,

1. Update OpenStudio version in the Dockerfile. Change the first line to ``FROM nrel/openstudio:3.6.1``.
2. Fix weather file path. In ``buildstockbatch/aws/aws.py`` line 2049 loop, **epw_filename** has the following path as its value "../../../weather/XYZ.epw.gz" which causes an error in AWS. The path needs to be "XYZ.epw.gz" instead. I added the following line of code as a bug fix - ``epw_filename = epw_filename.split('/')[-1]`` at line 2051.
3. I got an email stating that AWS Lambda is dropping support for Python 3.7 (check [here](https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/)). It needs to be updated to Python 3.11. Additionally, can the entire buildstockbatch package be updated to run Python 3.11 on AWS?
4. The postprocessing script always runs after the simulation and it always terminates with errors. I currently run the **postprocessing.py** script separately to get the results. I would love to be able to run the postprocessing scripts through the EMR clusters.

Thank you for your help. :)

**Comment by nmerket** [comment]
Thanks @phgupta. The updates to the AWS workflow are still on a branch and weren't part of the v2023.06.0 release. It's still a work in progress and we're dealing with the bugs you mention above and some others issues as well with it. Once it's ready, you'll be the first to know.

**Comment by afontani** [comment]
Closing as this feature is actively being developed.
