### ISSUE TITLE
Retain OSM files for ResStock datasets

### ISSUE THREAD

**Issue by ejhw** [NREL/buildstockbatch#440]
**Is your feature request related to a problem? Please describe.**
A significant fraction of people that email [resstock@nrel.gov](mailto:resstock@nrel.gov) or post on Unmet hours are struggling with getting the osm or idf files for resstock samples.

From @shorowit:

> I was attempting to answer [this Unmet Hours question](https://unmethours.com/question/97705/whats-the-workflow-for-importing-the-nrel-hpxml-into-openstudio/) about how to take a 2022 EUSS HPXML file and generate the OpenStudio model, but found it surprisingly difficult. I did go ahead and document how to do it, though I expect it will be too difficult for many users.
>  
> Is there a reason we don't include the OpenStudio model alongside the HPXML file in the OEDI zip files? 
>  
> If we do want to make the process of going from HPXML -> OpenStudio models simpler, a couple improvements would be:
> - Update the HPXML file to use relative paths instead of Eagle paths everywhere.
> - Include more data files (like the Cambium emissions factors) in the OEDI zip.
> That would mean the user only has to do extra steps related to the EPW weather file.

**Describe the solution you'd like**
@whiphi92 suggests including an option in the `server_directory_cleanup` block to retain osm files

**Describe alternatives you've considered**
See above

**Additional context**
None

**Comment by nmerket** [comment]
This [already exists](https://github.com/NREL/resstock/blob/develop/measures/ServerDirectoryCleanup/measure.rb#L28-L30). It just wasn't set in the EUSS run. 

cc @joseph-robertson @whiphi92
