### ISSUE TITLE
"net" columns are empty in ResStock timeseries

### ISSUE THREAD

**Issue by rajeee** [NREL/buildstockbatch#446]
**Describe the bug**
 Buildings that don't have PV will not have PV and "net" output columns in the timeseries. This can lead to errors downstream when sum or other aggregations are calculated since the empty columns are interpreted as zero. Interpretation of 0 is correct for the PV energy consumption columns but will be incorrect for the "net" columns such as "fuel_use__electricity__net__kwh", "energy_use__net__kbtu" etc.

**To Reproduce**
 Look at any existing ResStock run.

**Expected behavior**
The concatenated timeseries files uplaod to s3 will have a correct "net" column values even if the raw timeseries csv from the simulation doesn't.

**Additional context**
This is causing problem for the EUSS processing.

**Comment by shorowit** [comment]
I think we can make this change in OS-HPXML. https://github.com/NREL/OpenStudio-HPXML/issues/1676

**Comment by rajeee** [comment]
Change made in OS-HPXML.
