### ISSUE TITLE
Running Buildstockbatch on a new HPC (other than eagle)

### ISSUE THREAD

**Issue by BenChenshun** [NREL/buildstockbatch#469]
**Unable to run user-defined project file after successfully pull the resstock docker image to local HPC**
I was able to run the sample project_national/national_baseline.yml on my local HPC after I pulled the resstock image (3.2.0), but once I defined my own .yml file (for example, sample the number of datapoints as 3000), then it failed to run. The debug mode showed the following error: KeyError: 'BuildExistingModel.building_id'. I'm hoping someone could help me resolve this issue.

**Comment by nmerket** [comment]
buildstockbatch is not really meant to run on any HPC system. There's so much variability in the configuration and we don't have access to test and ensure it works across a wide variety of systems.

**Comment by joshuaeh** [comment]
@BenChenshun check your ResStock/OpenStudio-HPXML/OpenStudio/Buildstockbatch versions. I got this error when running buildstockbatch with files leftover from an old version of ResStock. Also, make sure that if you're using a precomputed sampler that the buildstock.csv file has been generated from the current version.
