### ISSUE TITLE
Enable Commercial Usage of Master

### ISSUE THREAD

**Issue by rHorsey** [NREL/buildstockbatch#63]
Issue to track requirements for Commercial usage of buildstockbatch. Initial todos:

- [x] OpenStudio version abstraction in [base.py](https://github.com/NREL/buildstockbatch/blob/73b1ee67a64f21b4fc607a491a80fb219c0a3d2b/buildstockbatch/base.py#L38-L39) through yml
- [x] `sys_image_dir` abstraction in [eagle.py](https://github.com/NREL/buildstockbatch/blob/73b1ee67a64f21b4fc607a491a80fb219c0a3d2b/buildstockbatch/eagle.py#L33) and [hpc.py](https://github.com/NREL/buildstockbatch/blob/73b1ee67a64f21b4fc607a491a80fb219c0a3d2b/buildstockbatch/hpc.py#L75-L96) through yml
- [x] Add requests status code check in [hpc.py](https://github.com/NREL/buildstockbatch/blob/73b1ee67a64f21b4fc607a491a80fb219c0a3d2b/buildstockbatch/hpc.py#L75-L96) for pulling down singularity container
- [x] Include results directory protection behavior
- [x] Enable custom bundle option in [hpc.py](https://github.com/NREL/buildstockbatch/blob/73b1ee67a64f21b4fc607a491a80fb219c0a3d2b/buildstockbatch/hpc.py#L215) for non-linked gems (i.e. OpenStudio Standards)
- [x] Add commercial workflow
- [x] Enable precomputed sampling
- [x] Ensure lack of BuildingCharacteristicReport is not a problem

**Comment by asparke2** [comment]
@rHorsey can we close this issue? ComStock can definitely be run on local docker and on Eagle using the code on master.  I haven't tried testing AWS, but IMO that isn't worth keeping this issue over.

**Comment by nmerket** [comment]
Fixed in #238
